import express from "express";
import dotenv from "dotenv";
import "./models/Agent.js";
import "./models/User.js";
import "./models/Account.js";
import "./models/LOB.js";
import "./models/Carrier.js";
import "./models/Policy.js";
import uploadRoutes from "./routes/uploadRoutes.js";
import policyRoutes from "./routes/policyRoutes.js";
import messageRoutes from "./routes/messageRoutes.js";
import postMainRoutes from "./routes/postMain.js";
dotenv.config();
const app = express();
app.use(express.json());
app.use("/api/upload", uploadRoutes);
app.use("/api/policy", policyRoutes);
app.use("/api/message", messageRoutes);
app.use("/api", postMainRoutes);
app.get("/", (req, res) => res.send("API running successfully 🚀"));
export default app;
